site_name: Reefer Container Management Service
repo_url: https://github.com/ibm-cloud-architecture/refarch-kc-container-ms
nav:
  - Introduction: index.md
  - Analysis and design considerations: ES2DDD2MS.md
  - Different implementations:
    - Kafka Streams Implementation: kstreams/README.md
    - Springboot - Kafka and PostgreSQL Implementation: springboot/README.md
    - Python Flask and Kafka Implementation: flask/README.md
  - Deployments:
    - Pre-requisite: deployment.md
    - Run spring boot app locally: springboot/README.md
    - Continuous delivery: cicd.md
  - Run integration tests: tests.md
  - Container Predictive Maintenance: metrics.md
theme: 
  name: material
extra_css: ["extra.css"]
